### ISSUE TITLE
docs: No Setup Guide For Next.js App Router

### ISSUE THREAD

**Issue by Barzi-Ahmed** [trpc/trpc#5936] opened 2024-08-12 15:19 UTC
### Area of Improvement

It was extremenly frustrauting to me to not get or see setup guide in docs for Next.js (14) App Router. The current Next.js setup guide is only using Pages Router.

Please fix this as it is a very bad look for tRPC. 

### Link to related docs

https://trpc.io/docs/client/nextjs/setup

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5936">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5936/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5936/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment] 2024-08-19 10:05
_(Duplicate of #5277)_

We have a blog post of how you can do it in https://trpc.io/blog/trpc-actions, but it isn't a one-size-fits-all type of situation. The aforementioned example doesn't work well if you e.g. also want a React Native app to use the same endpoints.

In your situation - how did you end up setting up tRPC?

**Closed** 2024-08-28 12:06 UTC
Labels: 📚 documentation / examples
