### ISSUE TITLE
bug: inference errors in middleware and context 

### ISSUE THREAD

**Issue by omridevk** [trpc/trpc#5037] opened 2023-11-14 15:05 UTC
### Provide environment information

  System:
    OS: macOS 13.6.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 117.69 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.2.0 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 119.0.6045.123
    Chrome Canary: 121.0.6127.0
    Safari: 17.1
  npmPackages:
    @trpc/client: 10.43.2 => 10.43.2
    @trpc/react-query: 10.43.2 => 10.43.2
    @trpc/server: 10.43.2 => 10.43.2
    typescript: ^5.2.2 => 5.2.2

### Describe the bug

Hard to explain but I have this code: (create-context.ts)
```
import {inferAsyncReturnType} from '@trpc/server'
import type {
  CreateFastifyContextOptions,
  FastifyTRPCPluginOptions,
  // eslint-disable-next-line
} from '@trpc/server/adapters/fastify'

/**
 * Defines your inner context shape.
 * Add fields here that the inner context brings.
 */
export interface CreateInnerContextOptions extends Partial<CreateFastifyContextOptions> {}

export function createContext(config: Partial<FastifyTRPCPluginOptions<any>>) {
  return (outerOptions: CreateFastifyContextOptions) => {
    return createInternalContext(async (innerOptions) => {
      if (!outerOptions?.req || !outerOptions?.res) {
        return innerOptions
      }
      return {
        ...innerOptions,
        ...(await config?.trpcOptions?.createContext?.({
          req: outerOptions.req,
          res: outerOptions.res,
        })),
      }
    }, outerOptions)
  }
}

/**
 * Outer context. Used in the routers and will e.g. bring `req` & `res` to the context as "not `undefined`".
 *
 * @see https://trpc.io/docs/context#inner-and-outer-context
 */
async function createInternalContext<T>(
  createContextInner: (opts?: CreateInnerContextOptions) => T,
  opts: CreateFastifyContextOptions,
) {
  const contextInner = await createContextInner()
  return {
    ...contextInner,
    req: opts.req,
    res: opts.res,
  }
}

type LocalContext<T> = inferAsyncReturnType<typeof createInternalContext<T>>

export type Context<T> = T extends infer R ? LocalContext<R> : never

```

And this wrapper for creating trpc (make-trpc.ts):
```


import {initTRPC, TRPCError} from '@trpc/server'
import {authenticate} from '@mama/auth-plugin'
import {Context} from './create-context.js'
import {CreateFastifyContextOptions} from '@trpc/server/adapters/fastify'

export function makeTRPC<T>(config?: Parameters<typeof initTRPC.create>[0]) {
  const t = initTRPC.context<Context<T>>().create({
    errorFormatter(error) {
      return config?.errorFormatter?.(error) ?? error.shape
    },
  })

  function withAuth(authOptions: Parameters<typeof authenticate>[1]) {
    return t.middleware(async (opts) => {
      if (!(opts.ctx as any).req) {
        throw new TRPCError({code: 'INTERNAL_SERVER_ERROR', message: 'missing req object'})
      }
      try {
        const {auth} = await authenticate(
          (opts.ctx as Context<CreateFastifyContextOptions>).req,
          authOptions,
        )
        return opts.next({
          ctx: {
            ...(opts.ctx as Context<Partial<CreateFastifyContextOptions>>),
            auth,
          },
        })
      } catch (e) {
        throw new TRPCError({code: 'UNAUTHORIZED'})
      }
    })
  }

  return {
    router: t.router,
    publicProcedure: t.procedure,
    createProtectedProcedure: (options: Parameters<typeof authenticate>[1] = {}) =>
      t.procedure.use(withAuth(options)),
  }
}


```

This works fine in @trpc/server version 10.43.2, however, when upgrading to 10.43.3 I am getting the following error:
```

TS2345: Argument of type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
is not assignable to parameter of type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
Type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
is not assignable to type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
. Two different types with this name exist, but they are unrelated.
Types of property  unstable_pipe  are incompatible.
Type
<$Params extends import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/procedure").ProcedureParams<import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").AnyRootConfig, unknown, unknown, unknown, unknown, unknow...
is not assignable to type
<$Params extends import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/procedure").ProcedureParams<import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").AnyRootConfig, unknown, unknown, unknown, unknown, unknow...
. Two different types with this name exist, but they are unrelated.
Types of parameters  fn  and  fn  are incompatible.
Type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
is not assignable to type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
. Two different types with this name exist, but they are unrelated.
Type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
is not assignable to type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
. Two different types with this name exist, but they are unrelated.
Type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
is not assignable to type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareBuilder<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/pa...
. Two different types with this name exist, but they are unrelated.
Types of property  _middlewares  are incompatible.
Type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareFunction<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/p...
is not assignable to type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareFunction<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/p...
. Two different types with this name exist, but they are unrelated.
Type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareFunction<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/p...
is not assignable to type
import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/middleware").MiddlewareFunction<{ _config: import("/Users/omrikatz/Public/web/mono/packages/trpc-commons/node_modules/@trpc/server/dist/core/internals/config").RootConfig<{ ctx: import("/Users/omrikatz/Public/web/mono/p...
. Two different types with this name exist, but they are unrelated.
Types of parameters  opts  and  opts  are incompatible.
Type '{ ctx: Simplify<Overwrite<FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] extends object ? FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] : object, { ...; }>>; ... 5 more ...; next: { ...; }; }' is not assignable to type '{ ctx: Simplify<Overwrite<FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] extends object ? FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] : object, Overwrite<...>>>; ... 5 more ...; next: { ...; }; }'.
Types of property  ctx  are incompatible.
Type 'Simplify<Overwrite<FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] extends object ? FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] : object, { ...; }>>' is not assignable to type 'Simplify<Overwrite<FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] extends object ? FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] : object, Overwrite<...>>>'.
Type '((any[] | Date) & Overwrite<FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] extends object ? FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] : object, { ...; }>) | { [K in keyof Overwrite<...>]: Overwrite<...>[K]; }' is not assignable to type 'Simplify<Overwrite<FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] extends object ? FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] : object, Overwrite<...>>>'.
Type 'any[] & Overwrite<FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] extends object ? FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] : object, { ...; }>' is not assignable to type 'Simplify<Overwrite<FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] extends object ? FlatOverwrite<object, { ctx: Unwrap<Context<T>>; }>["ctx"] : object, Overwrite<...>>>'.
```

<img width="1254" alt="CleanShot 2023-11-14 at 17 05 09@2x" src="https://github.com/trpc/trpc/assets/9701896/8c9ffba8-47cb-4c7b-a592-f93bcdd1228f">

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter

### To reproduce

Sorry wasn't able to easily reproduce it in a new repo.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5037">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5037/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5037/pledge.svg">
</picture>
</a>

**Comment by omridevk** [comment] 2023-11-14 15:07
Maybe related to this:
https://github.com/trpc/trpc/pull/5017

**Comment by omridevk** [comment] 2023-11-14 15:11
This is kinda worrying to be honest, second regression I have found without any major version changes.
Love this library, but wondering how can I have confidence in updating versions if stuff may just break with a minor version change?

**Comment by omridevk** [comment] 2023-11-14 15:11
In our projects we always run "npm update" before we deploy stuff so this just breaks without any warning causing us the need to pin versions, which I want to avoid. 
Again thanks a lot for your hard work!

**Comment by jussisaurio** [comment] 2023-11-14 16:09
I'm sorry you're experiencing issues with the newest patch version and would definitely like to help, but I would really need some kind of way to reproduce your problem.

**Comment by omridevk** [comment] 2023-11-14 17:11
not sure how I can make `makeTRPC` non generic, how will I type the context when using the makeTRPC?

**Comment by omridevk** [comment] 2023-11-14 17:12
the idea was that I can do something like this:
``` const {router} = makeTRPC<{myContext: string}>() ```

**Comment by omridevk** [comment] 2023-11-14 17:12
we have a lot of microservices, every service can have different context

**Comment by jussisaurio** [comment] 2023-11-14 17:14
This also makes the error go away for me: `makeTRPC<TFoo extends CreateFastifyContextOptions>`

**Comment by jussisaurio** [comment] 2023-11-14 17:17
`TFoo extends object` also works

**Comment by jussisaurio** [comment] 2023-11-14 17:18
This would explain the error as well. `Overwrite` was changed to only overwrite keys of objects, and `T` with no object constraint works differently now. 

Still can't 100% explain to you the behavior, but if you can work with `makeTRPC` accepting a type argument with the `object` constraint I think this solves your immediate problem.

**Comment by omridevk** [comment] 2023-11-14 17:19
<img width="929" alt="CleanShot 2023-11-14 at 19 19 23@2x" src="https://github.com/trpc/trpc/assets/9701896/ab92729d-7b12-4690-8aac-a462d9549ece">
<img width="896" alt="CleanShot 2023-11-14 at 19 19 42@2x" src="https://github.com/trpc/trpc/assets/9701896/fda69f36-3ca9-4119-835b-6eeda5b368a8">

**Comment by omridevk** [comment] 2023-11-14 17:20
same error when changing to extend object

**Comment by jussisaurio** [comment] 2023-11-14 17:23
Ok, at this point I'm just going to need a better reproduction then :( since using your code sample the error goes away for me if I constrain `T` to `object`, sorry.

**Comment by omridevk** [comment] 2023-11-14 17:36
@jussisaurio 
Created this stackblitz:
https://stackblitz.com/edit/github-nqqlsq?file=src%2Fserver%2Fmake-trpc.ts,package.json,src%2Fserver%2Fcreate-context.ts,tsconfig.json

not sure why the error is still there regardless of the version

**Comment by omridevk** [comment] 2023-11-14 17:53
I just want to make a generic makeTRPC, I have no idea how to get it to work :(

**Comment by omridevk** [comment] 2023-11-14 18:01
@jussisaurio  can you share your code that you were able to get it work?

**Comment by Nick-Lucas** [comment] 2023-11-14 18:16
So I think the big pain is with typescript here, t.middleware has never been particularly good because Typescript has problems inferring its inputs/outputs properly in the chain. Partly this is related to the complexity of the types which v11 is going to dramatically improve. Lots of efforts to make this better but having done a 1000 line test file and project around this earlier in the year and abandoning it I suggest a different pattern for this type of thing

https://stackblitz.com/edit/github-nqqlsq-shycwu?file=src%2Fserver%2Fmake-trpc.ts

<img width="548" alt="image" src="https://github.com/trpc/trpc/assets/8896153/4c9545db-48ef-4a2f-84f0-d3e156ab5003">

**Comment by jussisaurio** [comment] 2023-11-14 18:55
Thanks for the stackblitz @omridevk .

I think we probably need to roll back [these changes](https://github.com/trpc/trpc/pull/5017) and replace them with an equivalent implementation that doesn't touch Overwrite.

The trouble is that tRPC types are complex enough that the only way to be able to make changes to internal types with confidence is to keep extending the regression test set.

**Comment by jussisaurio** [comment] 2023-11-14 19:13
@omridevk I rolled back the changes from #5017 and your stackblitz repro example still fails to compile for some reason :/

**Comment by jussisaurio** [comment] 2023-11-14 19:18
@JoeKarow you wouldn't happen to have a compact example of what stopped working in your project after upgrading to 10.43.3?

**Comment by jussisaurio** [comment] 2023-11-14 19:47
I probably have a fix for both @JoeKarow and @omridevk use cases (cloned @JoeKarow 's InReach repo to reproduce), but I need to find a way to write a test that fails with 10.43.3 so I can verify the fix

**Comment by JoeKarow** [comment] 2023-11-14 19:49
> @JoeKarow you wouldn't happen to have a compact example of what stopped working in your project after upgrading to 10.43.3?

@jussisaurio I can try and make a minimal repro a bit later.

**Comment by jussisaurio** [comment] 2023-11-14 20:17
I managed to repro this now. @sentry/node (whose trpc middleware you are using) is also constructing trpc middlewares using an unconstrained type parameter `T` which I think is something that both of your problems share. I'll post a PR with reproing test soon

**Comment by JoeKarow** [comment] 2023-11-14 21:18
> I managed to repro this now. @sentry/node (whose trpc middleware you are using) is also constructing trpc middlewares using an unconstrained type parameter `T` which I think is something that both of your problems share. I'll post a PR with reproing test soon
> 
> EDIT: @JoeKarow I arrived at this conclusion because I think you're experiencing errors with extending your `baseProcedure` which uses the Sentry middleware, but doing e.g. `t.procedure.use(isAuthed)` works fine.

Ah, yeah - it is the Sentry middleware that is causing it.. it looks like they're doing some changes on their end too. https://github.com/getsentry/sentry-javascript/issues/9536

**Comment by jussisaurio** [comment] 2023-11-14 21:27
To be clear, it's the change in tRPC that is causing it. It is just manifesting when using the sentry middleware. For example @omridevk is not using Sentry and experiencing a similar issue. Hopefully the linked PR resolves both.

**Comment by omridevk** [comment] 2023-11-14 23:28
@jussisaurio you are awesome man! thanks again

**Comment by lforst** [comment] 2023-11-15 07:51
@jussisaurio Maintainer of the Sentry middleware here. Is there anything we should do differently? We don't have any more changes lined up as we believe our type definition seems to be correct now. Thanks!

**Comment by jussisaurio** [comment] 2023-11-15 17:17
> @jussisaurio Maintainer of the Sentry middleware here. Is there anything we should do differently? We don't have any more changes lined up as we believe our type definition seems to be correct now. Thanks!

I don't think there's necessarily anything wrong with your implementation. 👍 

---

More generally:

I've been trying to root cause this bug today and although I do have a PR that ostensibly fixes the issue, I'm still not sure what the exact cause is. I think in your (Sentry's) case the `T` in your middleware gets inferred as `Promise<MiddlewareResult<U>>` where `U` is `ProcedureParams<AnyRootConfig, unknown, unknown, unknown, unknown, unknown, unknown>`, and where `AnyRootConfig` is

```
RootConfig<{
  ctx: any;
  meta: any;
  errorShape: any;
  transformer: any;
}>;
```

Given that the user-visible issue seems to be errors with mapping `ctx` correctly between middlewares, my suspicion is that since `any` behaves very bizarrely with conditional types (it becomes a union of both arms of the ternary type), that has something to do with it.

But this is at least 50% conjecture.

**Comment by KATT** [comment] 2023-11-17 12:35
Please try out `10.43.4` and open a new issue if you encounter anything related 🙏

**Comment by omridevk** [comment] 2023-11-21 05:52
@KATT  issue still persist when using 10.43.6 (different error but still doesn't work)

**Comment by omridevk** [comment] 2023-11-21 05:54
you can see the error here:
https://stackblitz.com/edit/github-nqqlsq?file=src%2Fserver%2Fmake-trpc.ts

**Comment by omridevk** [comment] 2023-11-21 06:00
> So I think the big pain is with typescript here, t.middleware has never been particularly good because Typescript has problems inferring its inputs/outputs properly in the chain. Partly this is related to the complexity of the types which v11 is going to dramatically improve. Lots of efforts to make this better but having done a 1000 line test file and project around this earlier in the year and abandoning it I suggest a different pattern for this type of thing
> 
> https://stackblitz.com/edit/github-nqqlsq-shycwu?file=src%2Fserver%2Fmake-trpc.ts
> 
> <img alt="image" width="548" src="https://user-images.githubusercontent.com/8896153/282880988-4c9545db-48ef-4a2f-84f0-d3e156ab5003.png">

@Nick-Lucas 
Using your solution still getting uknown types:
https://stackblitz.com/edit/github-nqqlsq-qku5qe?file=src/server/make-trpc.ts,package.json,src/server/create-context.ts

**Comment by Nick-Lucas** [comment] 2023-11-21 09:28
Interesting, I'm not quite sure what's going on there, some weirdness related to the intersection type of Context maybe? Had a play around to simplify the Context type and it's still happening, though I have had success in the last with this.

We've been playing with a different compromise internally which is more reliable as it's fighting typescript much less, just tested out for this case and it does also work here:

https://stackblitz.com/edit/github-nqqlsq-msqnp8?file=src%2Fserver%2Fmake-trpc.ts,package.json,src%2Fserver%2Fcreate-context.ts

```ts
  type WithAuthOpts = {
    req?: any;
  };
  function withAuth<TNext extends NextFuncHack>(
    next: TNext,
    { req }: WithAuthOpts
  ) {
    if (!req) {
      throw new TRPCError({
        code: 'INTERNAL_SERVER_ERROR',
        message: 'missing req object',
      });
    }
    try {
      return next({
        ctx: {
          // auth,
        },
      });
    } catch (e) {
      throw new TRPCError({ code: 'UNAUTHORIZED' });
    }
  }

  return {
    router: t.router,
    publicProcedure: t.procedure,
    createProtectedProcedure: () =>
      t.procedure.use((opts) =>
        withAuth(
          opts.next,

          // Context is an intersection type and has to be checked, but that's specific to this Context type
          { req: 'req' in opts.ctx ? opts.ctx.req : undefined }
        )
      ),
  };
```

<img width="395" alt="image" src="https://github.com/trpc/trpc/assets/8896153/9e5fa0d4-886f-4697-bb4b-3e299c8a75fe">

**Comment by jussisaurio** [comment] 2023-11-21 16:20
@omridevk try:

```
import { ProcedureBuilder, ProcedureParams } from '@trpc/server';

...

function withAuth2<T extends ProcedureParams>(builder: ProcedureBuilder<T>) {
```

**Comment by jussisaurio** [comment] 2023-11-21 16:23
Extending `ProcedureBuilder<any>` doesn't do what you want here; it basically infers all the procedure params as `any` instead of narrowing.

**Comment by jussisaurio** [comment] 2023-11-21 16:35
@omridevk I've added the example you gave as a new test to our test set (see link above), let me know if that implementation works for you

**Comment by Nick-Lucas** [comment] 2023-11-21 17:07
> @omridevk try:
> 
> ```
> import { ProcedureBuilder, ProcedureParams } from '@trpc/server';
> 
> ...
> 
> function withAuth2<T extends ProcedureParams>(builder: ProcedureBuilder<T>) {
> ```

Great point, that does fix it! Though I couldn't explain why that works. `extends X` should just mean 'any type which is at least this and puts anything in place of `any`' but that so often seems not to behave with our types 😳

**Comment by jussisaurio** [comment] 2023-11-21 17:32
Yeah I couldn't tell you why exactly that happens here. 🤷‍♂️

**Comment by jussisaurio** [comment] 2023-11-21 19:40
Closing this, feel free to ask to reopen if the problem still persists; the solution above (or the alternative by Nick) should work

**Closed by jussisaurio** 2023-11-21 19:40 UTC
Labels: @trpc/server, 🐛 bug: unconfirmed

**Comment by omridevk** [comment] 2023-11-24 11:47
@jussisaurio  issue still persist in 10.44.1
