### ISSUE TITLE
feat: Allow `invalidate()` to infer input types from `.` containing procedure names of parent routers

### ISSUE THREAD

**Issue by JonParton** [trpc/trpc#2759] opened 2022-09-19 21:08 UTC
### Describe the feature you'd like to request

In implementing #2713 I came across a possible issue prompted by @KATT 's thought provoking edge case #2737 .

The `invalidate()` function when used on a router must traverse all possible procedures on sub routers that could be effected by the invalidation and infer any possible `input` values that could be passed to filter them. 

Currently it does this by traversing all procedures of the current, and sub routers and getting all input types in a big Partial Union. 

However, as pointed out by @KATT we could have procedures with `.` in them. So consider the router below: 

```ts
export const appRouter = t.router({
  user: t.router({
    byId: t.procedure
      .input(
        z.object({
          id: z.string(),
        }),
      )
      .query(({ input }) => ({ user: { id: input.id } })),
  }),
  // A procedure that would appear to be in the user router. 
  'user.getAvatar': t.procedure
    .input(z.object({ userId: z.string() }))
    .query(({ input }) => ({ userId: input.userId, avatar: 'url' })),
});
```

if we then did an invalidate like: 
```
const utils = trpc.useContext()
utils.user.invalidate()
```

It would be invalidating both of the procedures defined above... This is because [we decided, at least initially](https://github.com/trpc/trpc/pull/2713#issuecomment-1249121655), to store procedures like the `.` defined one above with a key of `[[['user','getAvatar']], {userId: "10"}]`. This key puts it within the user router, even though it is defined in a parent router! 

This is not a huge issue, but it does mean we would miss the possible input filter of `userId: string` as `utils.user.invalidate()` searches the `user` router and any sub routers ... not the parent router where this is defined! 🤦

### Describe the solution you'd like to see

Ideally we would make sure that the input types available for `invalidate()` come from all possible queries that will be invalidated... even if defined on a parent (Or grand parent! etc) router.

We could possibly do this by traversing from the very top router and searching out all procedures that would match the path of the current router but this could get very expensive Typescript Performance wise 🤑... 

### Desribe alternate solutions

Alternatives are either:
- To disallow `.`'s in procedure names (Now that we have sub routers do we really need to allow it?!)
  - This would give the advantages of 
    - Avoiding conflicts like we can encounter in [this comment](https://github.com/trpc/trpc/pull/2713#issuecomment-1246956147).
    - Avoid funny looking proxy code like `trpc.posts['comments.getById'].useQuery({ id: 1 })`
    - Always knowing relevant type information for any procedures operating at a router level will be in the current or sub routers ... not spuriously above! 
- To change query keys used to keep the `.` defined procedures as a single element IE: `[["user.getAvatar"],{ userId:10 }]` or the example above `[["posts","comments.getById"], { id:1 }]`
  - This would require a big re write of how the `@trpc/react` client passes around query paths as it currently does the same behaviour as the keys and just creates a single `.` joined string of all elements. Making it indistiguishable between one properly generated using sub routers. [This is also true for the back end](https://github.com/trpc/trpc/pull/2713#issuecomment-1246956147) that considers `'user.all':t.procedure....` the same as `user: t.router({all:t.procedure...})` and just takes the definition of the last one defined in the router. 

### Additional information

Just a heads up - I'd happily help tackle this but some of it may go DEEP. I also may not have time to implement this quickly! 🙁

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by JonParton** [comment] 2022-09-19 21:12
As part of closing this we should also be able to implement [this test](https://github.com/trpc/trpc/blob/fe8517ffbedb5c8f5c5a9aa64fe20757e51e7468/packages/server/test/react/invalidateRouters.test.tsx#L414) that is currently disabled. 👍 (Or remove it if we remove the problem by implementing one of the alternatives)

**Comment by KATT** [comment] 2022-09-19 21:18
Is this not a duplicate of #2737?

**Comment by JonParton** [comment] 2022-09-19 21:34
> Is this not a duplicate of #2737?

It probably blurs the lines and it's why I have heavily referenced it ...  

#2737 that felt more about the `dx` of the query keys themselves but this is a specific problem that comes from allowing `.` names procedures and then splitting them for the query key and a concrete problem in the `invalidate()` `input` types. 

It is most definitely the same root cause though ... this one probably has more detail so could keep this if you did feel it was a pure duplicate? ...

**Comment by KATT** [comment] 2022-11-27 15:44
I think this isn't a great idea... will be quite confusing DX, will close this for now. Feel free to reopen if you have a real need for it in your app

**Closed by KATT** 2022-11-27 15:44 UTC
Labels: ✨ enhancement
