### ISSUE TITLE
feat: return `Promise` in `.listen()`

### ISSUE THREAD

**Issue by ravshansbox** [trpc/trpc#5345] opened 2024-01-16 20:30 UTC
### Provide environment information

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 181.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.14.1 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2.1

### Describe the bug

`.listen()` method should return a Promise object as:
1) if the port is static then we don't need a promise wrapper
2) if the port is dynamic then we need to wrap to a promise and wait for a `listening` event

### Link to reproduction

https://stackblitz.com/edit/stackblitz-starters-79vedc

### To reproduce

We can see in the console that the port is undefined

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5345">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5345/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5345/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment] 2024-01-18 14:37
That's a feature, not a bug.

**Comment by KATT** [comment] 2024-01-18 14:42
For anyone wondering how to address this: 

https://github.com/trpc/trpc/blob/e37e719b356f39931f1188df6a6e06c98f4e849c/packages/tests/server/adapters/standalone.test.ts#L53-L74

**Comment by ravshansbox** [comment] 2024-01-18 14:58
Not sure it's a feature, because for now when port is not provided undefined is being returned even if it's listening to it which is at least confusing, also port property in return value does not include type undefined, it's exactly a number

**Comment by KATT** [comment] 2024-01-18 15:00
It works how Node.js's built-in [`createServer` works](https://nodejs.org/api/http.html#httpcreateserveroptions-requestlistener)

We really don't add much sugar on top: https://github.com/trpc/trpc/blob/e37e719b356f39931f1188df6a6e06c98f4e849c/packages/server/src/adapters/standalone.ts#L47-L52

**Comment by KATT** [comment] 2024-01-18 16:07
```ts
import type http from 'http';

export function startHTTPServer(
  server: http.Server,
  ...args: Parameters<http.Server['listen']>
) {
  return new Promise<void>((resolve, reject) => {
    server.addListener('error', (err) => {
      reject(err);
    });
    server.addListener('listening', () => {
      resolve();
    });
    server.listen(...args);
  });
}

```

**Comment by KATT** [comment] 2024-01-19 09:20
This is a breaking change & I'm pretty sure we won't fix this for v11. V12 won't arrive for a long time, so I am just going to close this to maintain the issues a bit. 

I'm not opposed to doing it, but we won't do it now & you didn't offer to fix it yourself.

**Closed by KATT** 2024-01-19 09:20 UTC
Labels: @trpc/server
