### ISSUE TITLE
feat: React Server Components & Server Actions 

### ISSUE THREAD

**Issue by josvanos** [trpc/trpc#4431] opened 2023-05-26 12:49 UTC
### Describe the feature you'd like to request

The last couple of days I have been experimenting with the new Next app directory, in combination with server actions. I want to suggest a new part of TRPC ecosystem to fully embrace next 13.4 and the big changes react 18 brought. 

I don't have a precise clue how TRPC wants to implement next 13.4 and what the ideas are around server actions and server components. So maybe the below solution is redundant.

### Describe the solution you'd like to see

I would like to suggest the following API added to `@trpc/nextjs` and maybe even as a standalone package.

```ts
import { createServerHandlers } from `@trpc/nextjs`;
const f = createServerHandlers();

export const protectedProcedure = f.use(authMiddleware).  // authMiddleware is an example middleware, like how TRPC handles middleware

```

## server actions
The new api should allow the following idea in the example component snippet: 
```ts
import { protectedProcedure } from "@/utils/trpc";
import { cookies } from 'next/headers';

//  createOrder is now an exportable, validated server action and can be used as form action
export const createOrder = protectedProcedure.input(z.object({ product_id: z.number() })).action(async ({ctx,input}) => {
"use server";
// createOrder..
});

 
export default function CreateOrder({ productId }) {
  return (
    <form action={createOrder}>
      <button type="submit">Create order</button>
    </form>
  );
```

## server components 
For server components I would like to suggest the same kind of idea:
```ts
const getUserOrders = protectedProcedure.query(async ({ ctx }) => {
  return await prisma.orders.findMany({ 
       where : {
           user_id: ctx.user.id
        }
);
})

export default  async function UserOrdersPage() {
      const orders = await getUserOrders();

      return <OrdersTable orders={orders} />
}

```

## Advantages
- the action and server component query function could be exported and reused in other components
- The nicest part would that the function maybe integrated to the trpc router at some point: 
```ts
// example with the previous defined functions
export const ordersRouter = t.router({
createOrder: t.procedure.implement(createOrder),
getUserOrders: t.procedure.implement(getUserOrders) 
 })

// note: implement is here a magic method that knows to add it correcly to the router. 
// the specifics of this implement function are left-aside, but I think it should be possible
```

### Describe alternate solutions

other possible libaries: 
- https://github.com/pingdotgg/zact
- https://github.com/TheEdoRan/next-safe-action

However, I think TRPC could be the best solution (if it integrates with the app router)

### Additional information

I would really like to see suggestions or other enhancements and become aware of what the plans are with TRPC in the context of next 13.4!

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment] 2023-05-26 20:17
Hey!

I love your suggestions. We have already started working on this :)

- This is a duplicate of #3297 (please, share your suggestions there! 🙏 )
- We have some WIP of something we're experimenting with in https://github.com/trpc/examples-next-app-dir
- We are working on streaming `"use client"`-components' cache whilst server rendering
- We have a Discord-channel dedicated to Next 13, please join!

**Closed by KATT** 2023-05-26 20:17 UTC
