### ISSUE TITLE
bug(next): setting `ssr: true` parameter on method `createTRPCNext` throws error on 404

### ISSUE THREAD

**Issue by PiotrekPKP** [trpc/trpc#4084] opened 2023-03-26 12:56 UTC
### Provide environment information

**System:**
OS: Linux 6.1 Arch Linux
CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
Memory: 8.44 GB / 15.43 GB
Container: Yes
Shell: 5.1.16 - /bin/bash

**Binaries:**
Node: 19.6.1 - /usr/bin/node
Yarn: 1.22.19 - /usr/bin/yarn
npm: 9.1.2 - /usr/bin/npm

### Describe the bug

Setting the **`ssr: true`** parameter on method `createTRPCNext` causes the NextJS app to return an error instead of showing the 404 page on page that does not exist.

However, creating the `pages/404.tsx` file manually makes the 404 page show again.

**Error thrown:** `Application error: a client-side exception has occurred (see the browser console for more information).`
I also could not find any other information in the console.

### Link to reproduction

https://github.com/PiotrekPKP/trpc-404-srr-reproduction

### To reproduce

- clone the reproduction repo
- install packages
- run `npm run dev`
- go to page that does not exist, eg. `/page-not-found`

### Additional information

Submitting in response to https://github.com/t3-oss/create-t3-app/issues/1289

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment] 2023-03-26 17:50
The reproduction link doesn't work - might be #596?

**Comment by PiotrekPKP** [comment] 2023-03-26 18:17
> The reproduction link doesn't work - might be #596?

Sorry, forgot to change the visibility to public :D

**Comment by KATT** [comment] 2023-03-27 07:02
Did a repro in #4087 with some notes on how you can help if you want. I don't know if I'll have time this week to resolve this

**Comment by PiotrekPKP** [comment] 2023-03-27 07:43
> Did a repro in #4087 with some notes on how you can help if you want. I don't know if I'll have time this week to resolve this

I'll have a look at it :)

**Comment by KATT** [comment] 2023-03-27 07:48
Actually, this is not a bug in tRPC

I did a reproduction with an e2e test: https://github.com/KATT/next-getInitialProps-404

This behavior starts showing as soon as you do this: https://github.com/KATT/next-getInitialProps-404/blob/1d47105c661a325348648b2f0b945ca910a258bd/src/pages/_app.tsx#L8-L12

I think you can work around it with a custom `_error.js`-page

Can't be fixed in trpc

**Closed by KATT** 2023-03-27 07:48 UTC
Labels: 🐛 bug

**Comment by PiotrekPKP** [comment] 2023-03-27 08:01
So it seems like a bug in NextJS... thanks for helping out!
