### ISSUE TITLE
Error compiling trpc: TRPCError.d.ts(7,14): error TS2416

### ISSUE THREAD

**Issue by jld-adriano** [trpc/trpc#1927] opened 2022-05-24 11:05 UTC
Getting an error when compiling a project that uses trpc, here's the error, deps and tsconfig.json

### Error
```
../../node_modules/@trpc/server/dist/declarations/src/TRPCError.d.ts(7,14): error TS2416: Property 'cause' in type 'TRPCError' is not assignable to the same property in base type 'Error'.
#22 12.52   Type 'unknown' is not assignable to type 'Error | undefined'.
``` 

### relevant deps
```
"dependencies": {
    "@trpc/server": "^9.22.0"
  },
  "devDependencies": {
    "@types/node": "17.0.23",
    "typescript": "4.6.3"
  }
```

### tsconfig
```
{
  "compilerOptions": {
    "target": "esnext",
    "allowJs": true,
    "strict": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "module": "CommonJS",
    "resolveJsonModule": true,
    "incremental": true
  },
  "include": ["**/*.ts", "**/*.d.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by jlalmes** [comment] 2022-05-24 11:38
Duplicate of https://github.com/trpc/trpc/issues/1588

**Closed by jlalmes** 2022-05-24 11:38 UTC
