### ISSUE TITLE
bug: Autocompletion do not works when I exporting trpc client in nuxt | update Autocompletion stopped working when I installed all packages in monorepo opened in single webstorm, fixed by opening clients in separate webstorms

### ISSUE THREAD

**Issue by gustawdaniel** [trpc/trpc#4235] opened 2023-04-22 03:57 UTC
### Provide environment information

```
  System:
    OS: Linux 6.1 Fedora Linux 37 (Workstation Edition)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 51.33 GB / 62.50 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 9.6.1 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 111.0.1
  npmPackages:
    @trpc/client: ^10.20.0 => 10.20.0 
    @trpc/server: ^10.20.0 => 10.20.0 
```

### Describe the bug

Argument type {not_exist: string} is not assignable to parameter type OverwriteIfDefined<unknown, {provider?: ZodNativeEnum<any>["_input"], from_lang?: ZodNativeEnum<any>["_input"], to_lang?: ZodNativeEnum<any>["_input"], from_text?: ZodString["_input"]}> | void 

Autocompletion works if i will define client (inside plugin definition)

![Zrzut ekranu z 2023-04-22 11-35-12](https://user-images.githubusercontent.com/16663028/233760442-f09f9b7d-d2c1-4535-bf00-61fbc26e0071.png)

```
TS2345: Argument of type '{ not_exist: string; }' is not assignable to parameter of type '{ from_text: string; from_lang: "uk" | "en" | "es" | "pl" | "de" | "fr" | "ru"; to_lang: "uk" | "en" | "es" | "pl" | "de" | "fr" | "ru"; provider: "deepl" | "reverso" | "google"; }'.   Object literal may only specify known properties, and 'not_exist' does not exist in type '{ from_text: string; from_lang: "uk" | "en" | "es" | "pl" | "de" | "fr" | "ru"; to_lang: "uk" | "en" | "es" | "pl" | "de" | "fr" | "ru"; provider: "deepl" | "reverso" | "google"; }'.
```

but when I exporting this client, then autocompletion stops working (in components when I need to use this client)

![Zrzut ekranu z 2023-04-22 11-34-27](https://user-images.githubusercontent.com/16663028/233760443-1c4981fa-a1d6-4f2d-8ef2-9713443e00d4.png)

```
Argument type {not_exist: string} is not assignable to parameter type OverwriteIfDefined<unknown, {provider?: ZodNativeEnum<any>["_input"], from_lang?: ZodNativeEnum<any>["_input"], to_lang?: ZodNativeEnum<any>["_input"], from_text?: ZodString["_input"]}> | void 
```

but checking arguments works.

I mean, that if I will write wrong arguments, I see red underline, but i can't see autocompletion or list of arguments in IDE.

### Link to reproduction

https://stackblitz.com/edit/github-y5a3ze?file=app.vue

### To reproduce

Described here:

https://github.com/nuxt/nuxt/issues/19281

### Additional information

the same problem is for both:

```
import { createTRPCProxyClient } from "@trpc/client";
import { createTRPCNuxtClient } from 'trpc-nuxt/client';
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by gustawdaniel** [comment] 2023-04-22 05:32
I will provide more context

![Zrzut ekranu z 2023-04-22 13-23-42](https://user-images.githubusercontent.com/16663028/233764308-d8935920-9d0a-4d82-9696-5a334e34f940.png)

It works in `composables/t.ts`


```typescript
// import { createTRPCNuxtClient as createTRPCProxyClient, httpBatchLink } from "trpc-nuxt/client";
import { AppRouter } from "trpc";
import { createTRPCProxyClient, httpBatchLink } from "@trpc/client";
import { useToken } from "~/composables/token";

const t = createTRPCProxyClient<AppRouter>({
  links: [
    httpBatchLink({
      url: 'http://localhost:2022/trpc',
      headers: () => {
        const headers: Map<string, string> = new Map<string, string>();

        const token = useToken();

        console.log("token", token.value);

        if (token.value) {
          headers.set('Authorization', `Bearer ${token.value}`);
        }

        return Object.fromEntries(headers);
      }
    }),
  ],
});

export function getTranslation(args) {
  return t.translate.query({
    // there autocompletion works perfect
  })
}

export {
  t
}
```

but when I am using exported "t" from "#imports" then I am losing autocompletion.

---

I was tried with `trpc-nuxt` but there are few cases (all bad)

- if i am reproducing tutorial https://trpc-nuxt.vercel.app/get-started/usage/simple then autocompletion not working
- if i am using my own trpc server out of nuxt project then it also not working
- if i am using useQuery instead of query in component with trpc-nuxt then autocompletion works in argument but not for result but does not work at all on runtime because in composable I do not have access to nuxt app, so trpc-nuxt can be used only in nuxt-plugin, but not in composable  

Currently I think about typing all queries in `composables/t.ts` where autocompletion works and exporting them, only problem is that I am not able to find how to import types/interfaces that are used to generate autocompletion.

**Comment by gustawdaniel** [comment] 2023-04-22 05:37
Connected issue:

https://youtrack.jetbrains.com/issue/WEB-58963

**Comment by gustawdaniel** [comment] 2023-04-22 06:10
I fixed my problem partially thanks to docs: https://trpc.io/docs/client/infer-types

1. I resigned from exporting tRPC client. Insead I wrapped all functions in `composable/t.ts` and exported functions

```typescript
import { AppRouter } from "trpc";
import { createTRPCProxyClient, httpBatchLink } from "@trpc/client";
import { useToken } from "~/composables/token";

const t = createTRPCProxyClient<AppRouter>({
  links: [
    httpBatchLink({
      url: 'http://localhost:2022/trpc',
      headers: () => {
        const headers: Map<string, string> = new Map<string, string>();

        const token = useToken();

        console.log("token", token.value);

        if (token.value) {
          headers.set('Authorization', `Bearer ${token.value}`);
        }

        return Object.fromEntries(headers);
      }
    }),
  ],
});

import type { inferRouterInputs, inferRouterOutputs } from '@trpc/server';
type RouterInput = inferRouterInputs<AppRouter>;
type RouterOutput = inferRouterOutputs<AppRouter>;


export function translate(args: RouterInput['translate']): Promise<RouterOutput['translate']> {
  return t.translate.query(args)
}

export function version(args: RouterInput['version']): Promise<RouterOutput['version']> {
  return t.version.query(args)
}
```

2. I resigned from `trpc-nuxt`. I am disappointed because it makes impression of ready, mature project but is much worse docummented than `createTRPCProxyClient`, and is too constrained. 

3. In components I have better autocompletion support

```typescript
import {version} from '#imports'

async function g() {
  const res = await version({});
  console.log(res);
}
```

but still there are few issues

![Zrzut ekranu z 2023-04-22 13-55-13](https://user-images.githubusercontent.com/16663028/233765599-ffc3c4fe-2753-4030-89dd-7d63d927f70f.png)

1. I see `ZodString` instead of `string`
2. `ZodNativeEnum` is not supported

but when I am exporting then I see good typing 

![Zrzut ekranu z 2023-04-22 13-58-22](https://user-images.githubusercontent.com/16663028/233765681-f7efe52e-cb74-4b2d-97ea-d766ee4807f7.png)

So I afraid that to get exact autocompletion I have to write this:

```
export function translate(args: {
  from_text: string,
  from_lang: "uk" | "en" | "es" | "pl" | "de" | "fr" | "ru",
  to_lang: "uk" | "en" | "es" | "pl" | "de" | "fr" | "ru",
  provider: "deepl" | "reverso" | "google"
}): Promise<RouterOutput["translate"]> {
  return t.translate.query(args);
```

What is even worse: `RouterOutput["translate"]` has great autocompletion in `composable/t.ts`

![Zrzut ekranu z 2023-04-22 14-03-10](https://user-images.githubusercontent.com/16663028/233765859-83b50fd8-5827-4e8a-8dfb-22e848d70985.png)

for example function `translate` should return `meanings` array and I can use it

![Zrzut ekranu z 2023-04-22 14-07-18](https://user-images.githubusercontent.com/16663028/233765999-f0debb7e-94bc-4fef-8a2d-d95432551c28.png)

but in component i am loosing it `pages/debug.vue`

![Zrzut ekranu z 2023-04-22 14-08-58](https://user-images.githubusercontent.com/16663028/233766080-9e554f8d-7f96-423e-9cab-d3502490c68b.png)

and I see these types with `any`.

```typesciript
const res: Simplify<Serialize<{provider: any, from_lang: any, to_lang: any, to_text: any, from_text: string, meanings: any}>> | {provider: any, from_lang: any, to_lang: any, to_text: any, from_text: string, meanings: any}
```

**Comment by Nick-Lucas** [comment] 2023-04-22 06:29
Thanks for all the information, though I can't see any issue in the Stackblitz you shared, are you sure you shared the right link?

From your original post, it looks like the type inference is working, but we're leaking an internal type: `OverwriteIfDefined` and it's producing undesirable editor feedback. Should be an easy fix if that's all, though a working reproduction would be tremendously helpful :)

**Comment by gustawdaniel** [comment] 2023-04-22 06:42
In next step i added exact typing of result

![Zrzut ekranu z 2023-04-22 14-20-56](https://user-images.githubusercontent.com/16663028/233766560-c3525717-d51c-47fe-a251-5433be3a69e5.png)

but only `strings` are autocompleted correctly

![Zrzut ekranu z 2023-04-22 14-32-38](https://user-images.githubusercontent.com/16663028/233767105-210f2909-d723-4312-a202-87f89d87eac4.png)

So i replaced `RouterOutput["translate"]` in `t.ts` by exactly the same type like on server

```typescript
{
  from_text: string,
  from_lang: Lang,
  to_text: string,
  meanings: translations['meanings'],
  to_lang: Lang,
  provider: TranslationProvider
}
```

and added

```
import {Lang, TranslationProvider, translations} from 'database'
```

executed command

```
pnpm dlx nuxi prepare
```

and now I have working autocompletion...

![Zrzut ekranu z 2023-04-22 14-36-16](https://user-images.githubusercontent.com/16663028/233767271-53262fc0-1bdc-4da4-a3e7-a1779f153bb9.png)

Finally I feel that I fixed it manually and I have to maintain types in two places:

- directly write what is returned type on backend
- directly write types on any client

So finally I ended with similar level of manual work as in graphql.

@Nick-Lucas thanks for your comment. I will create repo with minimal reproduction on github. Give me 1 hour for it.

**Comment by gustawdaniel** [comment] 2023-04-22 07:07
I prepared:
- nuxt app

https://github.com/gustawdaniel/trpc-monorepo-nuxt-prisma/blob/main/apps/nuxt/app.vue

- trpc package
https://github.com/gustawdaniel/trpc-monorepo-nuxt-prisma/blob/main/packages/trpc/src/index.ts

both are in `turborepo` with `pnpm` and I have proper autocompletion for `string`.

Now I will add enum.

**Comment by gustawdaniel** [comment] 2023-04-22 07:17
I added enum that should be 'a' | 'b'

https://github.com/gustawdaniel/trpc-monorepo-nuxt-prisma

![Zrzut ekranu z 2023-04-22 15-16-02](https://user-images.githubusercontent.com/16663028/233769353-abac0ef0-e1c6-475f-b410-17f024cccfbd.png)

but I see that it is mapped to string

![Zrzut ekranu z 2023-04-22 15-16-49](https://user-images.githubusercontent.com/16663028/233769376-1daef4b0-c662-4b74-936a-88bcdc5bbcd7.png)

**Comment by gustawdaniel** [comment] 2023-04-22 07:18
i fixed it changing

```
  version: publicProcedure.query(() => ({
```

to

```
  version: publicProcedure.query((): {enum: 'a' | 'b', version: string} => ({
```

but we can go deeper and try with enums from prisma

**Comment by gustawdaniel** [comment] 2023-04-22 07:31
I added `z.enum` to input and it works too

```
.input(z.object({ name: z.enum(['Yennefer', 'Triss']) }))
```

not perfectly, but I see autocompletions on this list

![Zrzut ekranu z 2023-04-22 15-24-26](https://user-images.githubusercontent.com/16663028/233769744-d5b3a98c-da7e-48fd-a29a-8eee1759bf97.png)

But `prisma` uses `z.nativeEnum` so lets try it.

Now I have

```
function getEnum() {
  return Math.random() > 0.5 ? 'a' : 'b'
}

export enum GirlName {
  Triss,
  Yennefer
}

export const appRouter = router({
  version: publicProcedure
    .input(z.object({
      name: z.enum(['Yennefer', 'Triss']),
      nativeEnum: z.nativeEnum(GirlName)
    }))
    .query((): {enum: 'a' | 'b', version: string} => ({
    version: "",
    enum: getEnum()
  }))
});
```

and

```
async function start() {
  // again it is correct, thanks to strict definition of result in trpc/src/index.ts
  // const v: {version: string, enum: "a" | "b"}
  const v = await version({
    name: 'Triss',
    nativeEnum: GirlName.Triss
  });
}
```

so native enums works, but I will add prisma in next step.

**Comment by gustawdaniel** [comment] 2023-04-22 07:50
I added simple `prisma.schema` that contains enum

```
enum Lang {
  en
  de
}

model words {
  id    String   @id @default(auto()) @map("_id") @db.ObjectId
  lang  Lang
  text  String
}
```

and created autocompletion that works.

![Zrzut ekranu z 2023-04-22 15-48-34](https://user-images.githubusercontent.com/16663028/233770677-d6557428-cbd8-40d7-89ff-cab8e0655ec7.png)

I need more time to checking where is problem. Maybe context make difference, because I skipped many elements of my real app in this minimal repo.

**Comment by gustawdaniel** [comment] 2023-04-22 08:11
I think it can be my case, because i have context that is higher order function

```
export function createContext(env: z.infer<typeof serverVariables & typeof envVariables>) {
  return ({ req }: CreateFastifyContextOptions) => {
    const user = getUser(req.headers.authorization);
    const auth = Boolean(user);
    const user_id = auth ? user?.sub ?? "" : "";
    return { user, auth, user_id, env };
  };
}

export type Context = inferAsyncReturnType<typeof createContext>;
```

I will try to go back to flat context and will pass env variables by `req`.

**Comment by gustawdaniel** [comment] 2023-04-22 08:41
I am giving up. I was fighting with this from yesterday.

I finished with two almost the same applications but one has working autocompletion, second not.

**Comment by Nick-Lucas** [comment] 2023-04-22 09:19
Since you have some reproductions we'll take a look, it does look like there's something we can improve, so re-opening this!

**Comment by gustawdaniel** [comment] 2023-04-22 12:23
I found exact place when I losing autocompletion and it seems to be not connected with `trpc`.

State before [ autocompletion works perfectly ]

I have only one app: `nuxt`, and two packages: `trpc` and `database`.

Then I created next package: `words-selector` that is not connected with `trpc` and `database` an even with `nuxt`.

My current suspections:
- webstorm have problem with caching when to many files are loaded to single project
- it can be connected with `pnpm` because 

---

I confirmed that autocompletion start and stopped working when I removing and creating `node_modules` in this new package.

**Comment by gustawdaniel** [comment] 2023-04-22 12:44
I am finally found ultimate working solution.

![Zrzut ekranu z 2023-04-22 20-32-33](https://user-images.githubusercontent.com/16663028/233784968-67328397-cf17-4fad-92d6-8c1b9e013c85.png)

I have the same code, that i had from the beginning. There was no problem with code.

On left: all monorepo opened in single webstorm. I mean that in single window I have all packages and apps. This is original repo when I observed this problem.

https://github.com/gustawdaniel/xue

autocompletion do not works or I have problems with incorrect autocompletion.

----

On right: I have opened only `apps/front` and autocompletion works perfectly without any hacks.

---

I do not know why exactly I experienced this issue, but when I indicating on type on left screen (all monorepo opened) then it sometimes takes few seconds to show hints.

I expect that calculating types was taking too long time, especially because of many `node_module` directories, that was excluded correctly in webstorm settings, but probably `trpc` was analysing all them and failed on timeout.

I do not know if it is possible to fix, if it is issue of webstorm, `trpc`.


There you can reproduce it installing all packages by `pnpm i` in file `apps/nuxt/app.vue`

https://github.com/gustawdaniel/trpc-monorepo-nuxt-prisma

**Comment by KATT** [comment] 2023-04-23 20:28
So, @Nick-Lucas, can we close this or not? 😅

**Comment by Nick-Lucas** [comment] 2023-04-23 20:33
Just caught up. Looks like it was a local usage issue in the end, thanks for the updates @gustawdaniel 

Yes it's generally a good idea to open the whole monorepo in your editor, under some setups typescript will need this to see everything

**Closed by Nick-Lucas** 2023-04-23 20:33 UTC
