### ISSUE TITLE
bug: cannot export trpc client if type is recursive and typescript is emitting declarations

### ISSUE THREAD

**Issue by emi2k01** [trpc/trpc#3943] opened 2023-03-08 04:01 UTC
### Provide environment information

```
  System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 14.56 GB / 31.27 GB
    Container: Yes
    Shell: 3.6.0 - /usr/bin/fish
  Binaries:
    Node: 19.7.0 - ~/.local/share/nvm/v19.7.0/bin/node
    Yarn: 1.22.19 - ~/.local/bin/yarn
    npm: 9.5.0 - ~/.local/share/nvm/v19.7.0/bin/npm
  Utilities:
    Make: 4.4 - /usr/bin/make
    GCC: 12.2.1 - /usr/bin/gcc
    Git: 2.39.2 - /usr/bin/git
    Clang: 15.0.7 - /usr/bin/clang
    FFmpeg: 5.1.2 - /usr/bin/ffmpeg
  Servers:
    Apache: 2.4.55 - /usr/bin/apachectl
  Virtualization:
    Docker: 23.0.1 - /usr/bin/docker
  IDEs:
    Nano: 7.2 - /usr/bin/nano
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Go: 1.20 - /usr/bin/go
    Perl: 5.36.0 - /usr/bin/perl
    Protoc: 3.21.12 - /usr/bin/protoc
    Python: 3.10.9 - /usr/bin/python
    Python3: 3.10.9 - /usr/bin/python3
  Databases:
    MySQL: 10.10.3 (MariaDB) - /usr/bin/mysql
    SQLite: 3.40.1 - /usr/bin/sqlite3
  Browsers:
    Firefox: 110.0
  Monorepos:
    Yarn Workspaces: 1.22.19

```

### Describe the bug

These are the following conditions to reproduce the bug.

1. A router's query must return a value with a recursive type.
2. Typescript must be configured to emit declarations (e.g. `composite: true`)

If a trpc proxy client is created with the router and then exported, typescript gives the following error:

```
Exported variable 'trpcClient' has or is using name 'SerializeObject' from external module '/home/user/src/work/gt/cs/qa/node_modules/@trpc/server/dist/shared/internal/serialize' but cannot be named
```

In the sandbox linked below you can see the error by hovering on `trpcClient`. You can also see the following key-value in `tsconfig.json`: `composite: true`.

### Link to reproduction

https://stackblitz.com/edit/github-kuehgz-gkrgy3?file=src%2Fpages%2Fapi%2Ftrpc%2F[trpc].ts%3AL15,src%2Fpages%2Findex.tsx,tsconfig.json,src%2Fpages%2F_app.tsx

Open the file `src/pages/api/trpc/[trpc].ts`

### To reproduce

1. Set `composite` to `true` in `tsconfig.json`
2. Make the output of a query a value whose type is recursive.
```
type Foo = { x: Foo | number };
// ...
myQuery: publicProcedure.query(async () => {
  return { a: 10 } as Foo;
})
```
3. Export a trpc client using the router that contains the previous query:
```
export const trpc = createTRPCProxyClient<typeof Router>({ links: [] });
```

### Additional information

Should `SerializeObject` be exported?

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by needim** [comment] 2023-03-08 06:49
Oh, I was creating a similar issue and saw this. It is probably related so instead of creating a new issue, I will provide info here. If it is not related please inform me so I can make a new issue.

My environment

```
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 73.70 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox Developer Edition: 109.0
    Safari: 16.3
  npmPackages:
    @trpc/server: ^10.14.1 => 10.14.1 
    typescript: ^4.6.3 => 4.9.5
```

Repro: https://stackblitz.com/edit/trpc-export-ts2742-ms5uy7?file=todoRoute.ts

<img width="498" alt="image" src="https://user-images.githubusercontent.com/271912/223639495-4228c2b2-7eb7-452e-955b-a0f91cf576f1.png">

<img width="649" alt="image" src="https://user-images.githubusercontent.com/271912/223639367-3ca9bdd1-c8c2-4602-b783-90aa63c89af2.png">

Additional info: In my repro, if you don't use Metadata it works.

**Comment by needim** [comment] 2023-03-08 09:17
> Oh, I was creating a similar issue and saw this. It is probably related so instead of creating a new issue, I will provide info here. If it is not related please inform me so I can make a new issue.
> 
> ```
> Exported variable 'router' has or is using name 'Meta' from external module
> ```
> 
> My environment
> 
> ```
>   System:
>     OS: macOS 13.2.1
>     CPU: (8) arm64 Apple M1
>     Memory: 73.70 MB / 8.00 GB
>     Shell: 5.8.1 - /bin/zsh
>   Binaries:
>     Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
>     Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
>     npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
>   Browsers:
>     Chrome: 110.0.5481.177
>     Firefox Developer Edition: 109.0
>     Safari: 16.3
>   npmPackages:
>     @trpc/server: ^10.14.1 => 10.14.1 
>     typescript: ^4.6.3 => 4.9.5
> ```
> 
> Repro: [stackblitz.com/edit/trpc-export-ts2742-ms5uy7?file=todoRoute.ts](https://stackblitz.com/edit/trpc-export-ts2742-ms5uy7?file=todoRoute.ts)
> 
> <img alt="image" width="498" src="https://user-images.githubusercontent.com/271912/223639495-4228c2b2-7eb7-452e-955b-a0f91cf576f1.png">
> 
> <img alt="image" width="649" src="https://user-images.githubusercontent.com/271912/223639367-3ca9bdd1-c8c2-4602-b783-90aa63c89af2.png">
> 
> Additional info: In my repro, if you don't use Metadata it works.
> 
> related #2994 #2717

Exporting type Meta fixed this. 👍

**Comment by Dealerpriest** [comment] 2023-03-09 13:16
I have the same issue (`Exported variable 'XXX' has or is using name 'SerializeObject' from external module "...path/to/@trpc/server/dist/shared/internal/serialize" but cannot be named.ts`).

My understanding is that the error in your specific case could be circumvented by explicitly typing the export. Typescript seems to be rather strict about having "direct" access to the types of exports, I guess in order to guarantee that the types can be inferred/found in the code that will import it.

In **To Reproduce, step 3** above I think this would amount to something like this:
```ts
import type { AppRouter } from 'wherever/you/have/your/AppRouter';
import { createTRPCProxyClient, type CreateTRPCProxyClient } from '@trpc/client';

export const trpc: CreateTRPCProxyClient<AppRouter>  = createTRPCProxyClient<AppRouter>(...stuffz...);
//                              ^---This is the important thing
```

BUT. In my specific case I'm using the trpcClient inside a rather complex type which is more or less impossible to set an explicit type for (it's a Pinia Storedefinition in a vue project). So I still think it would be valuable if trpc exposed the type `SerializeObject`, but perhaps marked it as internal.

**Closed** 2023-03-10 17:17 UTC
Labels: 🐛 bug
