### ISSUE TITLE
bug/(feat?): make trpc work with Next 14

### ISSUE THREAD

**Issue by ashutosh-c247** [trpc/trpc#4982] opened 2023-10-30 11:56 UTC
### Provide environment information

 System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 60.17 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.6.1 - ~/Library/pnpm/pnpm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.0
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.18.0 
    @trpc/client: ^10.43.0 => 10.43.0 
    @trpc/next: ^10.43.0 => 10.43.0 
    @trpc/react-query: ^10.43.0 => 10.43.0 
    @trpc/server: ^10.43.0 => 10.43.0 
    next: 14.0.0 => 14.0.0 
    react: ^18.2.0 => 18.2.0 
    typescript: 4.9.4 => 4.9.4

### Describe the bug

Getting this error when I am deploying trpc with NextJS 14 version. The production server crashed due to below error when I am deploying it to production but when I am testing the flow on localhost it works fine and good.

Also when I degraded the Nextjs version to 13.4.8 it works again but when I upgrade it to 14 version then getting below error on vercel deployment.

 ⨯ file:///var/task/node_modules/.pnpm/@trpc+react-query@10.43.0_@tanstack+react-query@4.18.0_@trpc+client@10.43.0_@trpc+server@10.4_xyoezmo6ballumn6zskppfxdhe/node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs:5
import React, { createContext, useRef, useState, useEffect, useCallback, useMemo } from 'react';
                ^^^^^^^^^^^^^
SyntaxError: Named export 'createContext' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const { createContext, useRef, useState, useEffect, useCallback, useMemo } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5) {
  page: '/'
}
 ⨯ file:///var/task/node_modules/.pnpm/@trpc+react-query@10.43.0_@tanstack+react-query@4.18.0_@trpc+client@10.43.0_@trpc+server@10.4_xyoezmo6ballumn6zskppfxdhe/node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs:5
import React, { createContext, useRef, useState, useEffect, useCallback, useMemo } from 'react';
                ^^^^^^^^^^^^^
SyntaxError: Named export 'createContext' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const { createContext, useRef, useState, useEffect, useCallback, useMemo } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5) {
  page: '/'
}
file:///var/task/node_modules/.pnpm/@trpc+react-query@10.43.0_@tanstack+react-query@4.18.0_@trpc+client@10.43.0_@trpc+server@10.4_xyoezmo6ballumn6zskppfxdhe/node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs:5
import React, { createContext, useRef, useState, useEffect, useCallback, useMemo } from 'react';
                ^^^^^^^^^^^^^
SyntaxError: Named export 'createContext' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const { createContext, useRef, useState, useEffect, useCallback, useMemo } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5) {
  page: '/'
}
Error: Runtime exited without providing a reason
Runtime.ExitError

### Link to reproduction

Not have the link

### To reproduce

Not any idea why it is happening.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4982">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4982/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4982/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment] 2023-10-30 21:36
actually, #4963 works apart from the websockets example that uses a custom server, so we need a reproduction here.

**Comment by Nick-Lucas** [comment] 2023-10-30 21:57
This appears to be a duplicate of #4957

**Comment by juliusmarminge** [comment] 2023-10-31 14:00
Your error looks like you're trying to import a hook or something in something that's not a client component. Can you provide a reproduction please?

**Comment by KATT** [comment] 2023-11-02 09:43
Hey there! :wave:

We appreciate the time you've taken to write this issue.

Unfortunately, we don't have the capacity to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself. 

Please feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).

**Closed by KATT** 2023-11-02 09:43 UTC
Labels: ⏮ needs reproduction, 🐛 bug: unconfirmed
