### ISSUE TITLE
@trpc/server - Inferrence quirk with ProcedureInputParserCustomValidatorEsque<TInput>

### ISSUE THREAD

**Issue by akomm** [trpc/trpc#511] opened 2021-06-11 14:54 UTC
`@trpc/server`: 7.0.0
Typescript tested: 4.2.4 & 4.3.2

There is a small, but annoying quirk with inference on the `ProcedureInputParserCustomValidatorEsque<TInput>`:

```ts
router()
  .mutation("write", {
    // 1. "a" parameter is inferred as unknown (=correct), but the return type is not inferred up the type tree
    input: (a) => "x",
    // 2. you need to explicitly type (a: unknown), for the inference of return type go up the tree:
    // input: (a: unknown) => "x"
    resolve({input}) {
      // input is resolved as unknown in case 1. and correctly as "string" in 2. case
    }
  })
```

**Comment by KATT** [comment] 2021-06-11 22:44
Not clear on what the problem is or what you'd expect as a solution. 🤔

May I ask why you don't use a validator?

**Comment by KATT** [comment] 2021-06-12 12:24
If you have a custom validator you need to assert and return a specific output, for example like this, from the tests: https://github.com/trpc/trpc/blob/6d092eb11dd74bbaa899d93d92a1935831294d7a/packages/server/test/validators.test.ts#L91-L96

**Comment by akomm** [comment] 2021-06-14 08:24
@KATT the problem is, that the return type of parser is not inferred, if you don't type the input as unknown

**Comment by KATT** [comment] 2021-06-14 09:20
Seems like it's a limitation with typescript inference and not specifically because of tRPC.

Anyway, there's a workaround & I think 99% of people using this tRPC are using validator libs

**Comment by akomm** [comment] 2021-06-17 12:38
I'm the 99%. I'm using io-ts. The way the input is typed just invites typescript to lose the type information in the chain. Had to create an ugly adapter for it to work... nwm

**Comment by KATT** [comment] 2021-06-17 14:36
Feel free to open a PR to fix it! I don't know how to do it and it feels like it'll take me several hours to resolve.

**Comment by akomm** [comment] 2021-06-21 08:46
I'm not quite sure why the issue is closed though. The problem with the typing is that you have 1 generic instantiation and 2 possible inference sources. So the fix would be BC break, but I don't see how it makes the situation "not an issue" ;P

**Comment by KATT** [comment] 2021-06-21 08:53
Have a look here if you want to address it - I won't myself.

- https://github.com/trpc/trpc/blob/main/packages/server/src/procedure.ts
- https://github.com/trpc/trpc/blob/main/packages/server/src/router.ts

**Comment by akomm** [comment] 2021-06-21 11:34
@KATT Thanks. Its same issue type, as [this next-auth issue](https://github.com/nextauthjs/next-auth/issues/2080). I'v posted a fix there. The issue is with the BC, I'll check back on this too.

**Comment by KATT** [comment] 2021-07-13 14:42
Closing this as I won't address it myself - if someone else experience problems related to this, feel free to nudge me [on twitter](https://twitter.com/alexdotjs).

**Closed by KATT** 2021-07-13 14:42 UTC
Labels: wontfix, ❔ question
