### ISSUE TITLE
bug: useQuery / ssg helper queryKeys inconsistent since beta.14, breaks hydration

### ISSUE THREAD

**Issue by c-ehrlich** [trpc/trpc#2984] opened 2022-10-11 21:54 UTC
### Provide environment information

```
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 93.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/Documents/dev/node_modules/.bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 106.1.44.108
    Chrome: 105.0.5195.125
    Edge: 106.0.1370.42
    Firefox: 105.0.1
    Safari: 15.6.1
  npmPackages:
    @tanstack/react-query: ^4.8.0 => 4.10.3 
    @trpc/client: 10.0.0-proxy-beta.14 => 10.0.0-proxy-beta.14 
    @trpc/next: 10.0.0-proxy-beta.14 => 10.0.0-proxy-beta.14 
    @trpc/react: 10.0.0-proxy-beta.14 => 10.0.0-proxy-beta.14 
    @trpc/server: 10.0.0-proxy-beta.14 => 10.0.0-proxy-beta.14 
    next: 12.3.1 => 12.3.1 
    react: 18.2.0 => 18.2.0 
    typescript: 4.7.4 => 4.7.4 
```

### Describe the bug

Since beta.14, queries called from `useQuery` use a new queryKey format - `[["router","procedure"],{"foo":"bar"}]`. However queries called from ssgHelpers still use the old queryKey format - `["router.procedure",{"foo":"bar"}]`

This means that when trying to hydrate using the ssg helpers, it will not hydrate because as far as React Query is concerned they are two different queries.

It was introduced in this commit: https://github.com/trpc/trpc/commit/1d187b11f83dade3a0e5643a66b3b4fe5974070c
And I think it needs to be fixed here: https://github.com/trpc/trpc/blob/df7b4e8f3a5d1d57a1dae719753c201ca8b20596/packages/react/src/ssg/ssgProxy.ts#L87

### Link to reproduction

https://github.com/c-ehrlich/trpc-querykey-bug

### To reproduce

clone the repo, `pnpm i`, `pnpm dev`

1. open localhost:3000, you will see two different querykeys:
  - ssg helper uses `["example.hello",{"text":"from tRPC"}]`
  - useQuery uses `[["example","hello"],{"text":"from tRPC"}]`

2. downgrade all tRPC packages to 10.0.0-proxy-beta-13
  - now both ssg helper and useQuery use `["example.hello",{"text":"from tRPC"}]`

### Additional information

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/8353666/195203396-f9daccea-9634-4412-88f9-eb6fa50b6b66.png">

Happy to work on fixing this bug, but also ok if a core maintainer just wants to get it done quick :)

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment] 2022-10-12 05:35
Possible duplicate of #2919

**Comment by KATT** [comment] 2022-10-12 07:02
#2977 should have resolved this. Released in `10.0.0-proxy-beta.18`.

Let me know if it it doesn't fix it.

**Comment by KATT** [comment] 2022-10-12 07:06
I tested the example and it works with `-beta.18`.

We've also added an e2e test to ensure this doesn't creep up again in #2979

**Closed** 2022-10-12 07:06 UTC
Labels: 🐛 bug: unconfirmed

**Comment by c-ehrlich** [comment] 2022-10-12 09:28
can confirm beta.18 fixes it
