### ISSUE TITLE
Type error in @trpc/server with TS 4.6

### ISSUE THREAD

**Issue by garronej** [trpc/trpc#1588] opened 2022-03-01 22:56 UTC
Hi @KATT,  
Thank you for this great library.  

I am reporting that the server types need updates after the latest typescript release (4.6):  

```bash
node_modules/@trpc/server/dist/declarations/src/TRPCError.d.ts:7:14 - error TS2416: Property 'cause' in type 'TRPCError' is not assignable to the same property in base type 'Error'.
  Type 'unknown' is not assignable to type 'Error | undefined'.

7     readonly cause?: unknown;
               ~~~~~


Found 1 error in node_modules/@trpc/server/dist/declarations/src/TRPCError.d.ts:7
```

![image](https://user-images.githubusercontent.com/6702424/156262690-0552b0f1-4b45-4172-b39c-6d5204b66219.png)

Best regards

**Comment by KATT** [comment] 2022-03-02 09:35
You probably want to disable [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck). I'll have a look at this when I can

**Comment by mechamobau** [comment] 2022-03-03 14:54
@KATT Maybe using a generic type to the `cause` with `unknown` as the default should fix the error, if it's needed I can work on this

**Comment by sachinraja** [comment] 2022-04-03 00:18
Solved this while working on #1597. The issue is that [in es2022 a `cause` property was added](https://github.com/tc39/proposal-error-cause). Not sure how to fix this without doing a breaking change.

**Comment by sachinraja** [comment] 2022-04-04 22:42
Fixed on the `next` branch

**Closed by sachinraja** 2022-04-04 22:42 UTC

**Comment by ArnaudBarre** [comment] 2022-05-03 10:33
For people running into this (skipLibCheck strangely doesn't work), change lib option in tsconfig to ES2021 (instead of ESNext/ES2022)
