### ISSUE TITLE
bug(example): CLIENT_FETCH_ERROR on examples-next-prisma-websockets-starter

### ISSUE THREAD

**Issue by helderjbe** [trpc/trpc#5505] opened 2024-02-21 16:55 UTC
### Provide environment information

 System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 434.78 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.15.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.2.1
  npmPackages:
    @tanstack/react-query: ^5.0.0 => 5.22.2 
    @trpc/client: npm:@trpc/client@next => 11.0.0-next-beta.289+27a9183d8 
    @trpc/next: npm:@trpc/next@next => 11.0.0-next-beta.289+27a9183d8 
    @trpc/react-query: npm:@trpc/react-query@next => 11.0.0-next-beta.289+27a9183d8 
    @trpc/server: npm:@trpc/server@next => 11.0.0-next-beta.289+27a9183d8 
    next: ^14.0.1 => 14.1.0 
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3 

### Describe the bug

I just set up the project on https://github.com/trpc/examples-next-prisma-websockets-starter. Right after following the README, I logged in with the Mocked GitHub option.
However, after sending messages and refreshing, I keep getting this error:
```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error undefined {
  error: {},
  url: 'http://localhost:3000/api/auth/session',
  message: undefined
}
```

Mind you, I didn't change anything in the codebase.

### Link to reproduction

https://github.com/trpc/examples-next-prisma-websockets-starter

### To reproduce

Clone the repo
Follow the install instructions
Play around with the app (after sign in), it will popup eventually

### Additional information

Digging a bit further, I realize that using Websockets with SSR: true in trpc.ts breaks the auth system if you're using the "database" strategy in next-auth. It just spams the log with the messages from bug above.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5505">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5505/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5505/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment] 2024-03-11 19:31
Closing as this is a duplicate of #4810

**Closed by KATT** 2024-03-11 19:31 UTC
Labels: 🙋‍♂️ help wanted, bug in documentation/example
