### ISSUE TITLE
bug: mutaion handler not run and always timeout in production only

### ISSUE THREAD

**Issue by duylddev** [trpc/trpc#6251] opened 2024-11-19 15:08 UTC
### Provide environment information

Production run in node:20-alpine so `npx envinfo --system` doesn't work
Binaries:
    Node: 20.18.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
  npmPackages:
    @tanstack/react-query: ^5.50.0 => 5.60.5
    @trpc/client: ^11.0.0-rc.446 => 11.0.0-rc.638+09a76869e
    @trpc/react-query: ^11.0.0-rc.446 => 11.0.0-rc.638+09a76869e
    @trpc/server: ^11.0.0-rc.446 => 11.0.0-rc.638+09a76869e
    next: ^15.0.1 => 15.0.3
    react: ^18.3.1 => 18.3.1
    typescript: ^5.5.3 => 5.6.3

### Describe the bug

- UI send mution request to server, input is a base64 content
- Nothing log show in server 
-  After 1.5min, the request is timeout
```
2024-11-19T13:04:23.130868265Z [TRPC] genMockup took 100244ms to execute
```
- trp timing middleware log, it mean the request went to trpc 
- not all tprc requests get this issues and not all the time
- it's not the only project I face this issue. But this time I want to submit the issue

### Link to reproduction

it's production bug, dev is fine

### To reproduce

```
genMockup: publicProcedure.input(z.string()).mutation(async ({ input }) => {
    console.log('start')

    const image = await printify.upload(input)
    console.log('uploaded image')

    const a = await printify.createMockups(image.id)
    console.log('created mockups')

    return a
  }),
  ```
```
2024-11-19T13:04:23.130868265Z [TRPC] genMockup took 100244ms to execute
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6251">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6251/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6251/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment] 2024-11-19 16:58
Which [link](https://trpc.io/docs/client/links) are you using on the client?

We can't really do anything with this without more info or a reproduction. Might be due to your hosting provider timing out requests or something too.

**Comment by KATT** [comment] 2024-11-25 19:48
Will have to close this, we can't help you here without a reproduction or more info, feel free to reopen a new issue or post in discussions if you need help

**Closed by KATT** 2024-11-25 19:48 UTC
Labels: ⏮ needs reproduction, 🐛 bug: unconfirmed
